server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/missyou?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 12345678
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true